In [43]:
import numpy as np
from scipy.io import loadmat
from scipy.optimize import linear_sum_assignment
import matplotlib.pyplot as plt
from scipy.io import loadmat
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from scipy.stats import chisquare

salinas = loadmat(r"C:\Users\erdem.hayat\Desktop\Masaüstü\Üni\İTÜ\Statistical Data Analyses for Computational Science\Salinas_corrected.mat")
print(salinas["salinas_corrected"])
salinas_gt = loadmat(r"C:\Users\erdem.hayat\Desktop\Masaüstü\Üni\İTÜ\Statistical Data Analyses for Computational Science\Salinas_gt.mat")
print("salinas_gt=",salinas_gt["salinas_gt"])

X = salinas.reshape(145*145,220)

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)

[[[290 381 585 ...  36  11  17]
  [290 381 519 ...  36  11  15]
  [290 381 585 ...  30  11  11]
  ...
  [373 482 594 ...   6   4   0]
  [373 482 659 ...   0   0   5]
  [305 393 655 ...   1   1  -3]]

 [[379 400 600 ...  32  11  15]
  [308 400 535 ...  28  15  13]
  [379 483 535 ...  26   5  15]
  ...
  [376 477 590 ...   3   0  -5]
  [376 477 590 ...   7   0  13]
  [305 393 655 ...   1   1  -3]]

 [[369 495 604 ...  29   9  17]
  [298 411 604 ...  23   5  13]
  [298 411 670 ...  27   7  13]
  ...
  [447 468 664 ...   4   7   0]
  [305 468 664 ...  14   7   2]
  [447 384 664 ...   6   1   4]]

 ...

 [[379 383 540 ...   6   5   9]
  [308 383 540 ...   8   5   5]
  [379 383 540 ...   4  -2   7]
  ...
  [367 387 661 ...  39  17  23]
  [367 470 661 ...  43  15  23]
  [438 470 596 ...  41  13  27]]

 [[314 479 604 ...   8   5   0]
  [314 396 539 ...   4   3   2]
  [385 396 539 ...   2   1   0]
  ...
  [367 387 661 ...  39  17  23]
  [367 470 661 ...  43  15  23]
  [376 489 674 ...  42  15  

AttributeError: 'dict' object has no attribute 'reshape'